spring:
 jpa:
  show-sql: true # 显示sql语句
  hibernate:
    ddl-auto: update
  database-platform: org.hibernate.dialect.H2Dialect
 datasource:
  url: jdbc:h2:file:./data/h2db #jdbc:h2:D:/h2/phantom #jdbc:h2:file:~/.h2/testdb jdbc\:h2\:file\:D\:\\testdb
  username: phantom
  password: phantom
  driver-class-name: org.h2.Driver