spring:
 jpa:
  show-sql: true # 显示sql语句
  hibernate:
    ddl-auto: update
  database-platform: org.hibernate.dialect.MySQL5Dialect
 datasource:
  url: jdbc:mysql://localhost:3306/phantom_blog?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
  username: root
  password: asd123456
  driver-class-name: com.mysql.jdbc.Driver